# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Delivery Company CI/CD

on: 
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore DeliveryCompany/DeliveryCompany.sln
    - name: Build
      run: dotnet build --no-restore DeliveryCompany/DeliveryCompany.sln
    - name: Install test runner (if needed on your runner)
      run: | 
          sudo apt-get update
          sudo apt-get install -y mstest

    - name: Run unit tests with MSTest
      run: |
          mstest /testcontainer:DeliveryCompany/UnitTests/bin/Debug/UnitTests.dll
